---
title: Central Balance Sheet Database - Information by Sector of Activity File
subtitle: Extraction Date - June 2023
date: 7 July 2023
doi: 10.17900/CB.CBA.Jun2023.V1
pdf-engine: pdflatex
execute:
  echo: false
format:
  html:
    toc: true
    theme: default
---

## Variables Description

| Name | Description | Unit of measurement | Start Time | End time | Changes in classification | Accounting Plan | Accounting Regime | Comments |
| :--------: | :-------------: | :-------: | :-----: | :-----: | :-----: | :-----: | :---: | :-------: |
| ano | Year of reference | years | 2006 | 2021 | no | na | na |  |
| **Identifiers** |
| tina | Anonymized Tax Identification Number | code | 2006 | 2021 | no | na | na |  |
| numordem | Number of order of the sector | code | 2006 | 2021 |  | na | na |  |
| **By Sector of Activity** |
| VF6105 | Portuguese classification of economic activities | code | 2006 | 2010 |  yes | POC | na | Q05-0544-Nota44-CAE-1 |
| VF53120 | Portuguese classification of economic activities (Rev. 3) | code | 2010 | 2021 | no | SNC | na | Q05A-05301A-CAE-1 |
| VF04106 | Internal Market - Total sales by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1405-1 |
| VF04107 | Internal Market - Total services by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1406-1 |
| VF04108 | Internal Market - Total purchases by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1407-1 |
| VF04109 | Internal Market - Total supplies and external services by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1408-1 |
| VF04110 | EU Market - Total sales by sector | euros | 2006 | 2010 | countries included in EU Market changed over time | POC | na | Q05-0544-Nota44-A1409-1 |
| VF04111 | EU Market - Total services by sector | euros | 2006 | 2010 | countries included in EU Market changed over time | POC | na | Q05-0544-Nota44-A1410-1 |
| VF04112 | EU Market - Total purchases by sector | euros | 2006 | 2010 | countries included in EU Market changed over time | POC | na | Q05-0544-Nota44-A1411-1 |
| VF04113 | EU Market - Total supplies and external services by sector | euros | 2006 | 2010 | countries included in EU Market changed over time | POC | na | Q05-0544-Nota44-A1412-1 |
| VF04114 | Extra-EU Market - Total sales by sector | euros | 2006 | 2010 | some countries entered/exited the EU over time | POC | na | Q05-0544-Nota44-A1413-1 |
| VF04115 | Extra-EU Market - Total services by sector | euros | 2006 | 2010 | some countries entered/exited the EU over time | POC | na | Q05-0544-Nota44-A1414-1 |
| VF04116 | Extra-EU Market - Total purchases by sector | euros | 2006 | 2010 | some countries entered/exited the EU over time | POC | na | Q05-0544-Nota44-A1415-1 |
| VF04117 | Extra-EU Market - Total supplies and external services by sector | euros | 2006 | 2010 | some countries entered/exited the EU over time | POC | na | Q05-0544-Nota44-A1416-1 |
| VF04118 | Total sales by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1417-1-soma |
| VF04119 | Total services by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1418-1-soma |
| VF04120 | Total purchases by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1419-1-soma |
| VF04121 | Total supplies and external services by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1420-1-soma |
| VF04124 | Total cost of goods sold and material consumed by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1423-1-soma |
| VF04122 | Cost of goods sold by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1421-1 |
| VF04123 | Cost of material consumed by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1422-1 |
| VF04125 | Variation in production by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1424-1 |
| VF04126 | Average number of employees by sector | number of people | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1425-1 |
| VF04129 | Total employee costs by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1428-1-soma |
| VF04127 | Employee costs - Salaries by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1426-1 |
| VF04128 | Employee costs - Others by sector | euros | 2006 | 2010 | no | POC | na | Q05-0544-Nota44-A1427-1 |
| VF15571 | Total sales by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6041-1-soma |
| VF15572 | Sales - Goods by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6042-1 |
| VF15573 | Sales - Finished and intermediate products; Subproducts, wastes and scrap; Products and work in progress by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6043-1 |
| VF15574 | Sales - Biological assets by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6044-1 |
| VF15575 | Services by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6045-1 |
| VF15576 | Purchases by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6046-1 |
| VF15577 | Supplies and external services by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6047-1 |
| VF15578 | Total cost of goods sold and material consumed by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6048-1-soma |
| VF15579 | Cost of goods sold and material consumed - Goods by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6049-1 |
| VF15580 | Cost of goods sold and material consumed - Raw and subsidiary materials and consumables by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6050-1 |
| VF15581 | Cost of goods sold and material consumed - Biological assets (purchases) by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6051-1 |
| VF15582 | Variation in production by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6052-1 |
| VF15583 | Average number of employees by sector | number of people | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6053-1 |
| VF15584 | Total employee expenses by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6054-1-soma |
| VF15585 | Employee expenses - Salaries by sector | euros | 2010 | 2021 | no | SNC | N,S,M | Q05A-05301A-A6055-1 |





|Legend |     |
| :---: | :--------------------: |
| na | Not Applicable |
| POC | Official Chart of Accounts |
| SNC	| Accounting Standards System |
| N	| International Accounting Standards |
| S	| Accounting and Financial Reporting Standards and Accounting and Financial Reporting Standards for Small-Sized Entities |
| M	| Accounting and Financial Reporting Standards for Micro-Entities |



## Time Series

|     |   2006 | 2007 | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 | 2015 | 2016 | 2017 | 2018 | 2019 | 2020 | 2021 |
| :---: |  :---: | :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: | :---: | :---: | :---: | :---: | :---: |
| ano | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| tina | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| numordem | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF6105 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF53120 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF04106 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04107 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04108 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04109 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04110 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04111 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04112 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04113 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04114 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04115 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04116 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04117 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04118 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04119 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04120 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04121 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04122 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04123 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04124 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04125 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04126 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04127 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04128 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF04129 | [✓] | [✓] | [✓] | [✓] | [✓] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] | [x] |
| VF15571 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15572 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15573 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15574 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15575 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15576 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15577 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15578 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15579 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15580 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15581 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15582 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15583 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15584 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15585 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |
| VF15586 | [x] | [x] | [x] | [x] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] | [✓] |



| Legend |   |
| :---: | :---------: |
| [✓] | Variable available in year t |
| [x] | Variable not available in year t |
