import Pkg

ENV["PYTHON"]=""
Pkg.add("PyCall")
Pkg.build("PyCall")
Pkg.add("Conda")
using Conda
Conda.runconda(`install jupyter --yes`)

Pkg.add("IJulia")
Pkg.add("StatsModels")

Pkg.add("ReadStat")
Pkg.add("StatFiles")
Pkg.add("ReadStatTables")
Pkg.add("Plots")
Pkg.add("QuantEcon")
Pkg.add("LinearAlgebra")
Pkg.add("StatsBase")
Pkg.add("Statistics")
Pkg.add("Distributions")
Pkg.add("Measures")
Pkg.add("LaTeXStrings")
Pkg.add("Random")
Pkg.add("Pandas")
Pkg.add("GLM")
Pkg.add("CSV")
Pkg.add("ShiftedArrays")
Pkg.add("Optim")
Pkg.add("NLSolversBase")
Pkg.add("DataFrames")
Pkg.add("DataFramesMeta")
Pkg.add("CategoricalArrays")
Pkg.add("Query")
Pkg.add("VegaLite")
Pkg.add("RegressionTables")
Pkg.add("Gadfly")
Pkg.add("KernelEstimator")

Pkg.precompile()
