pandoc -f markdown -t html -o manual_CBHP_JUN2019.html manual_CBHP_JUN2019.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_AMARC.html aux_files\codebook\cdbk_AMARC.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_Contas.html aux_files\codebook\cdbk_Contas.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_MG.html aux_files\codebook\cdbk_MG.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_Pessoal.html aux_files\codebook\cdbk_Pessoal.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_Rosto.html aux_files\codebook\cdbk_Rosto.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_AMARC.html aux_files\describe_dataset\dscr_AMARC.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_Contas.html aux_files\describe_dataset\dscr_Contas.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_MG.html aux_files\describe_dataset\dscr_MG.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_Pessoal.html aux_files\describe_dataset\dscr_Pessoal.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_Rosto.html aux_files\describe_dataset\dscr_Rosto.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_AMARC.html aux_files\descriptive_statistics\stat_AMARC.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_Contas.html aux_files\descriptive_statistics\stat_Contas.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_MG.html aux_files\descriptive_statistics\stat_MG.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_Pessoal.html aux_files\descriptive_statistics\stat_Pessoal.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_Rosto.html aux_files\descriptive_statistics\stat_Rosto.md
pandoc -f markdown -t html -o aux_files\variables_description\contas_snc_items.html aux_files\variables_description\contas_snc_items.md
pandoc -f markdown -t html -o aux_files\variables_description\indicadores_formula.html aux_files\variables_description\indicadores_formula.md
pandoc -f markdown -t html -o aux_files\variables_description\variables_pt_en.html aux_files\variables_description\variables_pt_en.md
pandoc -f markdown -t html -o aux_files\variables_description\var_rosto.html aux_files\variables_description\var_rosto.md
