pandoc -f markdown -t html -o manual_CB_JUN2020.html manual_CB_JUN2020.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_AMARC.html aux_files\codebook\cdbk_AMARC.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_byCAE.html aux_files\codebook\cdbk_byCAE.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_Contas.html aux_files\codebook\cdbk_Contas.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_FluxosCaixa.html aux_files\codebook\cdbk_FluxosCaixa.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_Indic.html aux_files\codebook\cdbk_Indic.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_MG.html aux_files\codebook\cdbk_MG.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_Pessoal.html aux_files\codebook\cdbk_Pessoal.md
pandoc -f markdown -t html -o aux_files\codebook\cdbk_Rosto.html aux_files\codebook\cdbk_Rosto.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_AMARC.html aux_files\describe_dataset\dscr_AMARC.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_byCAE.html aux_files\describe_dataset\dscr_byCAE.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_Contas.html aux_files\describe_dataset\dscr_Contas.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_FluxosCaixa.html aux_files\describe_dataset\dscr_FluxosCaixa.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_Indic.html aux_files\describe_dataset\dscr_Indic.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_MG.html aux_files\describe_dataset\dscr_MG.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_Pessoal.html aux_files\describe_dataset\dscr_Pessoal.md
pandoc -f markdown -t html -o aux_files\describe_dataset\dscr_Rosto.html aux_files\describe_dataset\dscr_Rosto.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_AMARC.html aux_files\descriptive_statistics\stat_AMARC.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_byCAE.html aux_files\descriptive_statistics\stat_byCAE.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_Contas.html aux_files\descriptive_statistics\stat_Contas.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_FluxosCaixa.html aux_files\descriptive_statistics\stat_FluxosCaixa.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_Indic.html aux_files\descriptive_statistics\stat_Indic.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_MG.html aux_files\descriptive_statistics\stat_MG.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_Pessoal.html aux_files\descriptive_statistics\stat_Pessoal.md
pandoc -f markdown -t html -o aux_files\descriptive_statistics\stat_Rosto.html aux_files\descriptive_statistics\stat_Rosto.md
pandoc -f markdown -t html -o aux_files\faq\faq.html aux_files\faq\faq.md
pandoc -f markdown -t html -o aux_files\variables_description\variables_pt_en.html aux_files\variables_description\variables_pt_en.md
pandoc -f markdown -t html -o aux_files\variables_description\var_amarc.html aux_files\variables_description\var_amarc.md
pandoc -f markdown -t html -o aux_files\variables_description\var_bycae.html aux_files\variables_description\var_bycae.md
pandoc -f markdown -t html -o aux_files\variables_description\var_cashflow.html aux_files\variables_description\var_cashflow.md
pandoc -f markdown -t html -o aux_files\variables_description\var_contas.html aux_files\variables_description\var_contas.md
pandoc -f markdown -t html -o aux_files\variables_description\var_emprego.html aux_files\variables_description\var_emprego.md
pandoc -f markdown -t html -o aux_files\variables_description\var_indicadores.html aux_files\variables_description\var_indicadores.md
pandoc -f markdown -t html -o aux_files\variables_description\var_mg.html aux_files\variables_description\var_mg.md
pandoc -f markdown -t html -o aux_files\variables_description\var_rosto.html aux_files\variables_description\var_rosto.md
